'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class AbcAnalysisEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AbcAnalysisEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AbcClass_Static() As DbSet(Of AbcClass_Static)
    Public Overridable Property AbcCodeItems() As DbSet(Of AbcCodeItem)
    Public Overridable Property AbcGroups() As DbSet(Of AbcGroup)
    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property TaskDatas() As DbSet(Of TaskData)
    Public Overridable Property UserPositionTypes() As DbSet(Of UserPositionType)
    Public Overridable Property Subinventories() As DbSet(Of Subinventory)

    Public Overridable Function LoadTasks() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("LoadTasks")
    End Function

    Public Overridable Function DeleteTasks(startDate As Nullable(Of Date), endDate As Nullable(Of Date)) As Integer
        Dim startDateParameter As ObjectParameter = If(startDate.HasValue, New ObjectParameter("StartDate", startDate), New ObjectParameter("StartDate", GetType(Date)))

        Dim endDateParameter As ObjectParameter = If(endDate.HasValue, New ObjectParameter("EndDate", endDate), New ObjectParameter("EndDate", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("DeleteTasks", startDateParameter, endDateParameter)
    End Function

    Public Overridable Function LoadAbc(abcGroup_id As Nullable(Of Integer)) As Integer
        Dim abcGroup_idParameter As ObjectParameter = If(abcGroup_id.HasValue, New ObjectParameter("AbcGroup_id", abcGroup_id), New ObjectParameter("AbcGroup_id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("LoadAbc", abcGroup_idParameter)
    End Function

End Class
