'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AbcCodeItem
    Public Property Id As Integer
    Public Property CodeItem As Long
    Public Property AbcGroup_id As Integer
    Public Property AbcClass_id As Integer

End Class
