'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TaskData
    Public Property Id As Integer
    Public Property XDate As Date
    Public Property YearNum As Integer
    Public Property MonthNum As Integer
    Public Property Subinventory As Integer
    Public Property Code As Long
    Public Property Category_Id As Integer
    Public Property UserPositionType_Id As Integer
    Public Property SalesOrder As Boolean
    Public Property Orders As Integer
    Public Property Tasks As Integer

End Class
